#Splash screen properties
#Fri Sep 04 20:47:11 EDT 2026
logoTexture=textures/gui/title/loading_mural.png
background=0xFFFFFF
font=0xFFF6E4
barBackground=0x1C1814
barBorder=0x4A3A2A
rotate=false
bar=0xE67A22
enabled=true
resourcePackPath=resources
logoOffset=0
forgeTexture=minecraft\:textures/gui/title/emblem_corner.png
fontTexture=textures/font/ascii.png
