#Splash screen properties
#Sat Sep 05 16:05:14 EDT 2026
logoTexture=textures/gui/title/loading_mural.png
background=0xFFFFFF
font=0xFFF6D0
barBackground=0x050403
barBorder=0x4A3A2A
rotate=false
bar=0xE67A22
enabled=true
resourcePackPath=resources
logoOffset=0
forgeTexture=minecraft\:textures/gui/title/emblem_corner.png
fontTexture=textures/font/ascii.png
